import Head from "next/head";
import { getSession, useSession } from "next-auth/react";
import Login from "@/components/Login";


export default function Home() {
  const { data: session } = useSession();

  if (!session) return <Login />;
  return (
    <>
    <Head>
        <title>Arynam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
                <h2 className={`mb-1 text-2xl font-semibold`}>
            Hello World
          </h2>
    </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}
